# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('randomization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionContext',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomization.Decision')),
            ],
        ),
    ]
