# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-05 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('randomization', '0002_decisioncontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRandomization',
            fields=[
            ],
            options={
                'verbose_name': 'Randomization user',
                'verbose_name_plural': 'Randomization for users',
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
        ),
        migrations.AddField(
            model_name='contexttag',
            name='dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contexttag',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
