# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-08 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomization', '0003_auto_20181005_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='randomization_message', to='push_messages.Message'),
        ),
    ]
