# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-26 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomization', '0004_auto_20181008_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRandomization',
        ),
        migrations.AlterModelOptions(
            name='decision',
            options={'ordering': ['-time']},
        ),
    ]
