# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-23 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomization', '0005_auto_20181026_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_template',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sent_message',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
