# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-24 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_suggestions', '0007_auto_20181124_0106'),
        ('randomization', '0006_auto_20181123_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='DecisionContext',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomization.Decision'),
        ),
    ]
