# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-22 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomization', '0007_auto_20181124_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
