# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-12 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomization', '0008_decision_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
