# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-13 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomization', '0011_decision_unavailable_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='imputed',
            field=models.BooleanField(default=False),
        ),
    ]
