# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-10 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomization', '0012_decision_imputed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnavailableReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='decision',
            name='available',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='unavailable_reason',
        ),
        migrations.AddField(
            model_name='unavailablereason',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomization.Decision'),
        ),
    ]
