# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-21 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomization', '0015_auto_20190711_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unavailablereason',
            name='reason',
            field=models.CharField(choices=[('unreachable', 'Unreachable'), ('notification-recently-sent', 'Notification recently sent'), ('not-sedentary', 'Not sedentary'), ('no-step-count-data', 'No step-count data'), ('on-vacation', 'On vacation'), ('disabled', 'Disabled'), ('service-error', 'service-error')], max_length=150),
        ),
    ]
