# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-27 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomization', '0018_auto_20200304_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionrating',
            name='decision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='randomization.Decision'),
        ),
    ]
