# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-19 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_messages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='external_id',
        ),
    ]
