# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-26 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_messages', '0002_remove_message_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('data', 'Data'), ('notification', 'Notification')], max_length=20),
        ),
    ]
