# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('push_messages', '0002_auto_20180821_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('type', models.CharField(choices=[('sent', 'Sent'), ('recieved', 'Recieved'), ('opened', 'Opened'), ('interacted', 'Interacted')], max_length=20)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push_messages.Message')),
            ],
        ),
        migrations.RemoveField(
            model_name='messagereciept',
            name='message',
        ),
        migrations.DeleteModel(
            name='MessageReciept',
        ),
    ]
