# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-08 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_messages', '0003_auto_20180917_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereceipt',
            name='type',
            field=models.CharField(choices=[('sent', 'Sent'), ('received', 'Received'), ('opened', 'Opened'), ('engaged', 'Engaged')], max_length=20),
        ),
    ]
