# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-03 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_messages', '0004_auto_20181008_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('Data', 'data'), ('Notification', 'notification')], default='data', max_length=20),
            preserve_default=False,
        ),
    ]
