# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-31 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_messages', '0005_message_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
