# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-29 18:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_messages', '0007_auto_20190531_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
