# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-29 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_messages', '0008_auto_20190829_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='collapse_subject',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
