# Generated by Django 3.1.7 on 2021-10-14 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0025_auto_20210909_0131'),
        ('push_messages', '0010_auto_20210306_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneSignalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=255)),
                ('app_key', models.CharField(max_length=255)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.study')),
            ],
        ),
    ]
