# Generated by Django 3.1.7 on 2021-12-30 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0025_auto_20210909_0131'),
        ('push_messages', '0011_onesignalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onesignalinfo',
            name='study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.study'),
        ),
    ]
