# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-26 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_reflection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='reflection_time',
        ),
        migrations.RemoveField(
            model_name='week',
            name='user',
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
