# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-04 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_reflection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflectiontime',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=15),
        ),
    ]
