# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-27 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_tasks', '0002_auto_20181219_1859'),
        ('weekly_reflection', '0002_auto_20181226_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflectiontime',
            name='daily_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daily_tasks.DailyTask'),
        ),
    ]
