# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-04 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_reflection', '0003_reflectiontime_daily_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflectiontime',
            name='day',
            field=models.CharField(choices=[('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=15),
        ),
    ]
