# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-08 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherforecast',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='cloud_cover',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
