# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-24 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20190624_2059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyWeatherForcast',
            new_name='DailyWeatherForecast',
        ),
    ]
