# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-24 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20190624_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyweatherforecast',
            name='category',
            field=models.CharField(choices=[('clear', 'Clear'), ('partially-cloudy', 'Partially Cloudy'), ('cloudy', 'Cloudy'), ('wind', 'Wind'), ('rain', 'Rain'), ('snow', 'Snow')], max_length=70),
        ),
        migrations.AlterField(
            model_name='dailyweatherforecast',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyweatherforecast',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
