# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-26 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20190624_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyweatherforecast',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailyweatherforecast',
            name='low',
            field=models.FloatField(),
        ),
    ]
