# Generated by Django 3.1.7 on 2022-03-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_zipcodeinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherforecast',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='weatherforecast',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='weatherforecast',
            name='time',
        ),
    ]
