# Generated by Django 3.1.7 on 2022-07-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_auto_20220317_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforecast',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
