# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-09 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(max_length=30)),
                ('from_number', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=255)),
                ('sms_sid', models.CharField(blank=True, default='', max_length=34)),
                ('account_sid', models.CharField(blank=True, default='', max_length=34)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
    ]
