# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-23 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsms',
            name='body',
            field=models.TextField(),
        ),
    ]
