# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-27 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('randomization', '0005_auto_20181026_0243'),
        ('django_celery_beat', '0006_auto_20180210_1226'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySuggestionConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='America/Los_Angeles', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySuggestionDailyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_suggestions.ActivitySuggestionConfiguration')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySuggestionServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('request_data', models.TextField()),
                ('request_time', models.DateTimeField()),
                ('response_code', models.IntegerField()),
                ('response_data', models.TextField()),
                ('response_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('morning', 'Morning'), ('lunch', 'Lunch'), ('midafternoon', 'Afternoon'), ('evening', 'Evening'), ('postdinner', 'Post dinner')], max_length=20)),
                ('hour', models.PositiveSmallIntegerField()),
                ('minute', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySuggestionDecision',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('randomization.decision',),
        ),
    ]
