# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-31 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestiontime',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
