# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-27 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysuggestiondailytask',
            name='category',
            field=models.CharField(default='foo', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitysuggestiondailytask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask'),
        ),
    ]
