# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-27 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_suggestions', '0002_auto_20181027_2130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivitySuggestionConfiguration',
            new_name='Configuration',
        ),
        migrations.RenameModel(
            old_name='ActivitySuggestionDailyTask',
            new_name='DailyTask',
        ),
        migrations.RenameModel(
            old_name='ActivitySuggestionServiceRequest',
            new_name='ServiceRequest',
        ),
    ]
