# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-31 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_suggestions', '0002_suggestiontime_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestiontime',
            name='timezone',
            field=models.CharField(default='America/Los_Angles', max_length=50),
        ),
    ]
