# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-02 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_suggestions', '0003_auto_20180731_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestiontime',
            name='timezone',
            field=models.CharField(default='America/Los_Angeles', max_length=50),
        ),
    ]
