# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-30 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_suggestions', '0003_auto_20181027_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='timezone',
        ),
    ]
