# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-25 00:48
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_suggestions', '0004_auto_20180802_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('request_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('request_time', models.DateTimeField()),
                ('response_code', models.IntegerField()),
                ('response_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('response_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
