# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-04 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_suggestions', '0004_remove_configuration_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='day_end_hour',
            field=models.PositiveSmallIntegerField(default=21),
        ),
        migrations.AddField(
            model_name='configuration',
            name='day_end_minute',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='day_start_hour',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='configuration',
            name='day_start_minute',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
