# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-06 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_suggestions', '0005_auto_20181104_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='service_initialized',
            field=models.BooleanField(default=False),
        ),
    ]
