# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-26 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomization', '0005_auto_20181026_0243'),
        ('activity_suggestions', '0005_activityservicerequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityServiceRequest',
            new_name='ActivitySuggestionServiceRequest',
        ),
        migrations.CreateModel(
            name='ActivitySuggestionDecision',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('randomization.decision',),
        ),
    ]
