# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-24 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomization', '0006_auto_20181123_2237'),
        ('activity_suggestions', '0006_configuration_service_initialized'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivitySuggestionDecision',
        ),
        migrations.CreateModel(
            name='ActivitySuggestionDecision',
            fields=[
                ('decision_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='randomization.Decision')),
            ],
            bases=('randomization.decision',),
        ),
    ]
