# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-26 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_suggestions', '0006_auto_20181026_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysuggestionservicerequest',
            name='request_data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activitysuggestionservicerequest',
            name='response_data',
            field=models.TextField(),
        ),
    ]
