# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-26 21:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_suggestions', '0007_auto_20181026_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionTimeConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='America/Los_Angeles', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='suggestiontime',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='suggestiontime',
            name='user',
        ),
        migrations.AddField(
            model_name='suggestiontime',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_suggestions.SuggestionTimeConfiguration'),
        ),
    ]
