# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-24 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('behavioral_messages', '0001_initial'),
        ('activity_suggestions', '0007_auto_20181124_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySuggestionMessageTemplate',
            fields=[
                ('messagetemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='behavioral_messages.MessageTemplate')),
            ],
            bases=('behavioral_messages.messagetemplate',),
        ),
    ]
