# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-29 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_suggestions', '0008_activitysuggestionmessagetemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytask',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyTask',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
