# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-29 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_suggestions', '0009_auto_20181129_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='day_end_hour',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='day_end_minute',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='day_start_hour',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='day_start_minute',
        ),
    ]
