# Generated by Django 3.1.7 on 2021-08-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_event_logs', '0003_auditentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlog',
            old_name='message',
            new_name='action',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='data',
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='status',
            field=models.CharField(choices=[('SCS', 'Success'), ('ERR', 'Error'), ('INF', 'Info'), ('DBG', 'Debug')], max_length=3),
        ),
    ]
