# Generated by Django 3.1.7 on 2021-08-04 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_event_logs', '0004_auto_20210801_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
