# Generated by Django 3.1.7 on 2021-08-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_event_logs', '0005_eventlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='status',
            field=models.CharField(choices=[('SCS', 'SCS'), ('ERR', 'ERR'), ('INF', 'INF'), ('DBG', 'DBG')], max_length=3),
        ),
    ]
