# Generated by Django 3.1.7 on 2021-08-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_event_logs', '0006_auto_20210810_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
