# Generated by Django 3.1.7 on 2022-06-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_event_logs', '0007_auto_20210813_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['user', 'timestamp'], name='user_event__user_id_e9ada7_idx'),
        ),
    ]
