version: '3'
services:
  client_build_ios: 
    build: 
      context: ./
      dockerfile: client_build.ios.Dockerfile
    volumes:
      - ./client:/client
      - ./credentials:/credentials
      - client-platforms:/client/platforms
      - client-node-modules:/client/node_modules
      - client-gradle-cache:/root/.gradle/caches
  client_android:
    build:
      context: ./
      dockerfile: client-android.Dockerfile
    env_file:
      - credentials/.env-production
    environment: 
      - BUILD_PLATFORM=android
      - BUILD_VERSION=2.3.2
      - HEARTSTEPS_URL=https://dev.heartsteps.net/api
    volumes:
      - ./client:/client
      - ./credentials:/credentials
      - client-platforms:/client/platforms
      - client-node-modules:/client/node_modules
      - client-gradle-cache:/root/.gradle/caches
volumes:
  client-platforms:
  client-node-modules:
  pgdata:
  client-gradle-cache:
  