# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-01 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0003_servicerequest_name'),
        ('anti_sedentary', '0002_auto_20190212_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiSedentaryServiceRequest',
            fields=[
                ('servicerequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_requests.ServiceRequest')),
            ],
            bases=('service_requests.servicerequest',),
        ),
    ]
