# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-10 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anti_sedentary', '0003_antisedentaryservicerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antisedentarydecision',
            name='sedentary',
        ),
    ]
