# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-11-24 01:09
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0011_auto_20191014_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardParticipant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('participants.participant',),
            managers=[
                ('summaries', django.db.models.manager.Manager()),
            ],
        ),
    ]
