# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-02 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('randomization', '0007_auto_20181124_0106'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('behavioral_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('service_initialized', models.BooleanField(default=False)),
                ('day_start_hour', models.PositiveSmallIntegerField(default=6)),
                ('day_start_minute', models.PositiveSmallIntegerField(default=0)),
                ('day_end_hour', models.PositiveSmallIntegerField(default=21)),
                ('day_end_minute', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalkingSuggestionDecision',
            fields=[
                ('decision_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='randomization.Decision')),
            ],
            bases=('randomization.decision',),
        ),
        migrations.CreateModel(
            name='WalkingSuggestionMessageTemplate',
            fields=[
                ('messagetemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='behavioral_messages.MessageTemplate')),
            ],
            bases=('behavioral_messages.messagetemplate',),
        ),
    ]
