# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-10 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walking_suggestions', '0003_configuration_impute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='impute',
            new_name='impute_context',
        ),
    ]
