# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-11 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walking_suggestions', '0004_auto_20190110_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='impute_context',
        ),
    ]
