# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-11 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walking_suggestions', '0005_remove_configuration_impute_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='service_initialized',
        ),
        migrations.AddField(
            model_name='configuration',
            name='service_initialized_date',
            field=models.DateField(null=True),
        ),
    ]
