# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-12 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walking_suggestions', '0006_auto_20190211_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
