# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-08 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walking_suggestions', '0009_nightlyupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nightlyupdate',
            options={'ordering': ['day']},
        ),
    ]
