# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-25 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walking_suggestions', '0011_auto_20190508_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='pooling',
            field=models.BooleanField(default=False),
        ),
    ]
