# Generated by Django 3.1.7 on 2021-05-19 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('behavioral_messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_requests', '0009_auto_20200507_1513'),
        ('randomization', '0020_auto_20210306_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoutPlanningDecision',
            fields=[
                ('decision_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='randomization.decision')),
            ],
            bases=('randomization.decision',),
        ),
        migrations.CreateModel(
            name='BoutPlanningMessageTemplate',
            fields=[
                ('messagetemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='behavioral_messages.messagetemplate')),
            ],
            bases=('behavioral_messages.messagetemplate',),
        ),
        migrations.CreateModel(
            name='BoutPlanningServiceRequest',
            fields=[
                ('servicerequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_requests.servicerequest')),
            ],
            bases=('service_requests.servicerequest',),
        ),
        migrations.CreateModel(
            name='BoutPlanningConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bout_planning_configuration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
