# Generated by Django 3.1.7 on 2021-05-19 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomization', '0020_auto_20210306_1849'),
        ('bout_planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boutplanningservicerequest',
            name='servicerequest_ptr',
        ),
        migrations.DeleteModel(
            name='BoutPlanningDecision',
        ),
        migrations.DeleteModel(
            name='BoutPlanningServiceRequest',
        ),
    ]
