# Generated by Django 3.1.7 on 2021-05-20 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bout_planning', '0003_genericmessagemodel_genericmessagesentlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoutPlanningMessageTemplate',
        ),
    ]
