# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-28 00:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitbit_api', '0042_auto_20190227_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_id', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('average_heart_rate', models.IntegerField(null=True)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitAccount')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='FitbitActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FitbitDailyUnprocessedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitAccount')),
            ],
        ),
        migrations.CreateModel(
            name='FitbitDay',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('_timezone', models.CharField(default='UTC', max_length=50)),
                ('step_count', models.PositiveIntegerField(default=0)),
                ('_distance', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
                ('average_heart_rate', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitAccount')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='FitbitMinuteStepCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('steps', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitAccount')),
            ],
        ),
        migrations.AddField(
            model_name='fitbitdailyunprocesseddata',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit_activities.FitbitDay'),
        ),
        migrations.AddField(
            model_name='fitbitactivity',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitbit_activities.FitbitActivityType'),
        ),
        migrations.AlterUniqueTogether(
            name='fitbitday',
            unique_together=set([('account', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='fitbitdailyunprocesseddata',
            unique_together=set([('day', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='fitbitactivity',
            unique_together=set([('account', 'fitbit_id')]),
        ),
    ]
