# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-27 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0043_auto_20190228_0054'),
        ('fitbit_activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitMinuteHeartRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('heart_rate', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitAccount')),
            ],
        ),
    ]
