# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-27 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_activities', '0004_auto_20190621_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbitday',
            name='completely_updated',
            field=models.BooleanField(default=False),
        ),
    ]
