# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-09-01 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_activities', '0005_fitbitday_completely_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbitday',
            name='minutes_worn',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
