# Generated by Django 3.1.7 on 2021-03-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_activities', '0006_fitbitday_minutes_worn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitactivity',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitbitdailyunprocesseddata',
            name='payload',
            field=models.JSONField(),
        ),
    ]
