# Generated by Django 3.1.7 on 2021-04-14 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0052_fitbitaccountsummary'),
        ('fitbit_activities', '0007_auto_20210306_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitActivitySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_worn', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fitbit_api.fitbitaccount')),
                ('last_fitbit_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fitbit_activities.fitbitactivity')),
            ],
        ),
    ]
