# Generated by Django 3.1.7 on 2021-10-07 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_activities', '0008_fitbitactivitysummary'),
    ]

    operations = [
        migrations.RunSQL(sql="CREATE TABLE fitbit_activities_fitbitminuteheartrate_backup AS SELECT * FROM fitbit_activities_fitbitminuteheartrate;", reverse_sql=migrations.RunSQL.noop),
    ]
