# Generated by Django 3.1.7 on 2021-10-07 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_activities', '0009_backup_fbmhr'),
    ]

    operations = [
        migrations.RunSQL(sql="ALTER TABLE fitbit_activities_fitbitminuteheartrate RENAME TO fitbit_activities_fitbitminuteheartrate_temp;", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="DELETE FROM fitbit_activities_fitbitminuteheartrate_temp;", reverse_sql=migrations.RunSQL.noop),
    ]
