# Generated by Django 3.1.7 on 2021-10-14 04:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_activities', '0012_auto_20211007_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitminuteheartrate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
