# Generated by Django 3.1.7 on 2022-07-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_activities', '0014_auto_20220707_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitactivitytype',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
