# Generated by Django 3.1.7 on 2022-07-12 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0055_auto_20220318_2230'),
        ('fitbit_activities', '0015_auto_20220712_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbitactivitytype',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitbit_api.fitbitaccount'),
        ),
    ]
