# Generated by Django 3.1.7 on 2021-05-26 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0020_auto_20201129_0128'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('cohort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='participants.cohort')),
            ],
        ),
        migrations.CreateModel(
            name='Conditionality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1024)),
                ('module_path', models.CharField(max_length=1024, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LogPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LogSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('frequency', models.CharField(max_length=20, null=True)),
                ('admins', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.study')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('cohort_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlm.cohortassignment')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
            ],
        ),
        migrations.CreateModel(
            name='LogContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtime', models.DateTimeField(auto_now_add=True)),
                ('value', models.TextField(blank=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlm.logobject')),
                ('purpose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nlm.logpurpose')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlm.logsubject')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('studytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlm.studytype')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionalityParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_fullname', models.CharField(max_length=1024)),
                ('period_begin', models.DateTimeField(auto_now_add=True)),
                ('period_finish', models.DateTimeField(null=True)),
                ('value', models.CharField(max_length=255)),
                ('value_type', models.CharField(max_length=255)),
                ('conditionality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nlm.conditionality')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.participant')),
            ],
        ),
        migrations.AddField(
            model_name='conditionality',
            name='studytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlm.studytype'),
        ),
        migrations.AddField(
            model_name='cohortassignment',
            name='studytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlm.studytype'),
        ),
        migrations.AddIndex(
            model_name='logcontents',
            index=models.Index(fields=['-logtime'], name='nlm_logcont_logtime_d568a2_idx'),
        ),
        migrations.AddIndex(
            model_name='logcontents',
            index=models.Index(fields=['subject', 'object', 'purpose'], name='nlm_logcont_subject_6f5d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='logcontents',
            index=models.Index(fields=['subject', 'purpose'], name='nlm_logcont_subject_a4ab22_idx'),
        ),
        migrations.AddIndex(
            model_name='logcontents',
            index=models.Index(fields=['purpose', 'object'], name='nlm_logcont_purpose_3b2410_idx'),
        ),
        migrations.AddIndex(
            model_name='logcontents',
            index=models.Index(fields=['object'], name='nlm_logcont_object__27eff1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conditionalityparameter',
            unique_together={('conditionality', 'participant', 'parameter_fullname', 'period_begin', 'period_finish')},
        ),
        migrations.AlterUniqueTogether(
            name='conditionality',
            unique_together={('module_path', 'studytype')},
        ),
    ]
