# Generated by Django 3.1.7 on 2021-05-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studytype',
            name='frequency',
            field=models.CharField(default='hourly', max_length=20),
        ),
        migrations.AlterField(
            model_name='studytype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
