# Generated by Django 3.1.7 on 2021-05-27 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlm', '0002_auto_20210526_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyassignment',
            name='study',
        ),
        migrations.DeleteModel(
            name='ParticipantAssignment',
        ),
        migrations.DeleteModel(
            name='StudyAssignment',
        ),
    ]
