# Generated by Django 3.1.7 on 2021-04-13 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlm', '0002_cohortassignment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantassignment',
            name='cohort_assignment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='nlm.cohortassignment'),
            preserve_default=False,
        ),
    ]
