# Generated by Django 3.1.7 on 2021-04-14 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlm', '0003_participantassignment_cohort_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohortassignment',
            name='user',
        ),
    ]
