# Generated by Django 3.1.7 on 2021-04-26 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlm', '0003_remove_participantassignment_studytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LogPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LogSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LogContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtime', models.DateTimeField(auto_now_add=True)),
                ('value', models.TextField(blank=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlm.logobject')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nlm.logpurpose')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlm.logsubject')),
            ],
        ),
        migrations.AddIndex(
            model_name='logcontents',
            index=models.Index(fields=['-logtime'], name='nlm_logcont_logtime_d568a2_idx'),
        ),
        migrations.AddIndex(
            model_name='logcontents',
            index=models.Index(fields=['subject', 'object', 'purpose'], name='nlm_logcont_subject_6f5d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='logcontents',
            index=models.Index(fields=['subject', 'purpose'], name='nlm_logcont_subject_a4ab22_idx'),
        ),
        migrations.AddIndex(
            model_name='logcontents',
            index=models.Index(fields=['purpose', 'object'], name='nlm_logcont_purpose_3b2410_idx'),
        ),
        migrations.AddIndex(
            model_name='logcontents',
            index=models.Index(fields=['object'], name='nlm_logcont_object__27eff1_idx'),
        ),
    ]
