# Generated by Django 3.1.7 on 2021-04-26 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0020_auto_20201129_0128'),
        ('nlm', '0004_auto_20210426_2101'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conditionality',
            unique_together={('name', 'studytype')},
        ),
        migrations.RemoveField(
            model_name='conditionality',
            name='user',
        ),
        migrations.CreateModel(
            name='ConditionalityParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_fullname', models.CharField(max_length=1024)),
                ('period_begin', models.DateTimeField(auto_now_add=True)),
                ('period_finish', models.DateTimeField(null=True)),
                ('value', models.CharField(max_length=255)),
                ('value_type', models.CharField(max_length=10)),
                ('conditionality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nlm.conditionality')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.participant')),
            ],
            options={
                'unique_together': {('conditionality', 'participant', 'parameter_fullname', 'period_begin', 'period_finish')},
            },
        ),
    ]
