# Generated by Django 3.1.7 on 2021-05-27 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nlm', '0004_auto_20210527_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreloadedLevelSequenceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('whenUploaded', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(max_length=255)),
                ('numberOfDays', models.IntegerField()),
                ('numberOfSequences', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'nickname')},
            },
        ),
        migrations.CreateModel(
            name='PreloadedLevelSequenceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_serial_number', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PreloadedLevelSequenceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_serial_number', models.IntegerField()),
                ('is_used', models.BooleanField(default=False)),
                ('sequence_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlm.preloadedlevelsequencefile')),
            ],
            options={
                'unique_together': {('sequence_file', 'sequence_serial_number')},
            },
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
