# Generated by Django 3.1.7 on 2021-04-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlm', '0005_conditionality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionality',
            name='module',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
