# Generated by Django 3.1.7 on 2021-04-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlm', '0005_auto_20210426_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionalityparameter',
            name='value_type',
            field=models.CharField(max_length=255),
        ),
    ]
