# Generated by Django 3.1.7 on 2021-06-03 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0020_auto_20201129_0128'),
        ('nlm', '0006_preloadedlevelsequencelevel_sequence_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelLineAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_assigned', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
                ('preloaded_sequence_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nlm.preloadedlevelsequenceline')),
                ('study_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlm.studytype')),
            ],
        ),
        migrations.CreateModel(
            name='LevelAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('level', models.IntegerField()),
                ('line_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlm.levellineassignment')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
            ],
        ),
    ]
