# Generated by Django 3.1.7 on 2021-04-30 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0020_auto_20201129_0128'),
        ('nlm', '0006_auto_20210426_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionalityparameter',
            name='conditionality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='nlm.conditionality'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conditionalityparameter',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.participant'),
        ),
    ]
