# Generated by Django 3.1.7 on 2021-06-09 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0020_auto_20201129_0128'),
        ('nlm', '0007_levelassignment_levellineassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('value', models.CharField(max_length=50)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
            ],
        ),
    ]
