# Generated by Django 3.1.7 on 2021-04-30 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0020_auto_20201129_0128'),
        ('nlm', '0008_auto_20210430_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionalityparameter',
            name='conditionality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nlm.conditionality'),
        ),
        migrations.AlterField(
            model_name='conditionalityparameter',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.participant'),
        ),
        migrations.AlterField(
            model_name='logcontents',
            name='purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nlm.logpurpose'),
        ),
    ]
