# Generated by Django 3.1.7 on 2021-06-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlm', '0008_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preloadedlevelsequencefile',
            name='nickname',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='preloadedlevelsequencefile',
            unique_together=set(),
        ),
    ]
