# Generated by Django 3.1.7 on 2021-06-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlm', '0009_auto_20210609_2239'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='logcontents',
            name='nlm_logcont_subject_6f5d3f_idx',
        ),
        migrations.RemoveIndex(
            model_name='logcontents',
            name='nlm_logcont_subject_a4ab22_idx',
        ),
        migrations.RemoveIndex(
            model_name='logcontents',
            name='nlm_logcont_purpose_3b2410_idx',
        ),
        migrations.RemoveIndex(
            model_name='logcontents',
            name='nlm_logcont_object__27eff1_idx',
        ),
        migrations.RemoveIndex(
            model_name='logcontents',
            name='nlm_logcont_logtime_8eff8c_idx',
        ),
        migrations.RemoveField(
            model_name='logcontents',
            name='object',
        ),
        migrations.RemoveField(
            model_name='logcontents',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='logcontents',
            name='subject',
        ),
        migrations.AddField(
            model_name='logcontents',
            name='object_str',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logcontents',
            name='purpose_str',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logcontents',
            name='subject_str',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='logcontents',
            index=models.Index(fields=['-logtime', 'subject_str'], name='nlm_logcont_logtime_817a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='logcontents',
            index=models.Index(fields=['subject_str', 'object_str', 'purpose_str'], name='nlm_logcont_subject_8a5124_idx'),
        ),
        migrations.AddIndex(
            model_name='logcontents',
            index=models.Index(fields=['subject_str', 'purpose_str'], name='nlm_logcont_subject_f3133c_idx'),
        ),
        migrations.AddIndex(
            model_name='logcontents',
            index=models.Index(fields=['purpose_str', 'object_str'], name='nlm_logcont_purpose_ae5d04_idx'),
        ),
        migrations.AddIndex(
            model_name='logcontents',
            index=models.Index(fields=['object_str'], name='nlm_logcont_object__ee9dfa_idx'),
        ),
    ]
