# Generated by Django 3.1.7 on 2021-06-17 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlm', '0011_auto_20210617_0257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogObject',
        ),
        migrations.DeleteModel(
            name='LogPurpose',
        ),
        migrations.DeleteModel(
            name='LogSubject',
        ),
    ]
