# Generated by Django 3.1.7 on 2021-03-23 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_messages', '0010_auto_20210306_1849'),
        ('walking_suggestion_surveys', '0002_configuration_treatment_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='push_messages.message'),
        ),
        migrations.AddField(
            model_name='decision',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='walking_suggestion_surveys.walkingsuggestionsurvey'),
        ),
    ]
