# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-29 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import weeks.models


class Migration(migrations.Migration):

    dependencies = [
        ('weeks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
