# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-04 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weeks', '0002_week_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['start_date']},
        ),
    ]
