# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-06 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeks', '0003_auto_20190104_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='confidence',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='minutes',
            field=models.IntegerField(null=True),
        ),
    ]
