# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-06 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weeks', '0004_auto_20190306_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='minutes',
            new_name='goal',
        ),
    ]
