# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-21 17:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weeks', '0006_auto_20190414_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBarrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyBarrierOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='week',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklybarrier',
            name='barrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='weeks.WeeklyBarrierOption'),
        ),
        migrations.AddField(
            model_name='weeklybarrier',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_barriers_set', to='weeks.Week'),
        ),
    ]
