# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-21 18:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weeks', '0008_auto_20190821_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeksurvey',
            name='barrier_options_raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
