# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-21 20:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weeks', '0009_weeksurvey_barrier_options_raw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeksurvey',
            name='barrier_options_raw',
        ),
        migrations.AddField(
            model_name='week',
            name='_barrier_options',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
