# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-21 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeks', '0010_auto_20190821_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='will_barriers_continue',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], max_length=50, null=True),
        ),
    ]
