# Generated by Django 3.1.7 on 2021-03-01 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weeks', '0011_week_will_barriers_continue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weeks.weeksurvey'),
        ),
    ]
