# Generated by Django 3.1.7 on 2021-03-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeks', '0012_auto_20210301_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='_barrier_options',
            field=models.JSONField(null=True),
        ),
    ]
