# Generated by Django 3.1.7 on 2022-03-17 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0025_auto_20210909_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudySetting',
            fields=[
                ('key', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.study')),
            ],
        ),
    ]
