# Generated by Django 3.1.7 on 2021-09-08 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bout_planning_notification', '0005_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_value', models.FloatField(default=0.5336150691164231)),
                ('return_bool', models.BooleanField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
