# Generated by Django 3.1.7 on 2021-09-08 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bout_planning_notification', '0006_randomdecision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomdecision',
            name='random_value',
            field=models.FloatField(default=0.6796978582646444),
        ),
        migrations.CreateModel(
            name='BoutPlanningDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_bool', models.BooleanField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
