# Generated by Django 3.1.7 on 2021-09-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bout_planning_notification', '0007_auto_20210908_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomdecision',
            name='random_value',
            field=models.FloatField(),
        ),
    ]
