# Generated by Django 3.1.7 on 2021-09-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bout_planning_notification', '0010_auto_20210908_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutplanningdecision',
            name='data',
            field=models.JSONField(default=None, null=True),
        ),
    ]
