# Generated by Django 3.1.7 on 2021-09-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bout_planning_notification', '0011_boutplanningdecision_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutplanningdecision',
            name='when_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
