# Generated by Django 3.1.7 on 2021-09-21 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('push_messages', '0010_auto_20210306_1849'),
        ('bout_planning_notification', '0012_boutplanningdecision_when_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoutPlanningNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bout_planning_notification.boutplanningdecision')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bout_planning_notification.level')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push_messages.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
