# Generated by Django 3.1.7 on 2021-09-22 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_messages', '0010_auto_20210306_1849'),
        ('bout_planning_notification', '0013_boutplanningnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutplanningnotification',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bout_planning_notification.boutplanningdecision'),
        ),
        migrations.AlterField(
            model_name='boutplanningnotification',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bout_planning_notification.level'),
        ),
        migrations.AlterField(
            model_name='boutplanningnotification',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='push_messages.message'),
        ),
        migrations.DeleteModel(
            name='RandomDecision',
        ),
    ]
