# Generated by Django 3.1.7 on 2021-12-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_question_published'),
        ('bout_planning_notification', '0016_boutplanningmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustWalkJitaiDailyEma',
            fields=[
                ('survey_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.survey')),
            ],
            bases=('surveys.survey',),
        ),
        migrations.CreateModel(
            name='JustWalkJitaiDailyEmaQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.question')),
            ],
            bases=('surveys.question',),
        ),
    ]
