# Generated by Django 3.1.7 on 2021-12-15 03:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bout_planning_notification', '0017_justwalkjitaidailyema_justwalkjitaidailyemaquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONSurvey',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('structure', models.JSONField(default={})),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
