# Generated by Django 3.1.7 on 2021-12-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bout_planning_notification', '0018_jsonsurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonsurvey',
            name='structure',
            field=models.JSONField(default=dict),
        ),
    ]
