# Generated by Django 3.1.7 on 2021-12-15 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bout_planning_notification', '0019_auto_20211215_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastItemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('used_index', models.IntegerField()),
                ('jsonsurvey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bout_planning_notification.jsonsurvey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
