# Generated by Django 3.1.7 on 2021-12-22 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participants', '0025_auto_20210909_0131'),
        ('bout_planning_notification', '0020_lastitemlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('when_used', models.DateTimeField(default=None, null=True)),
                ('sequence_text', models.TextField(default='1,2,3,4,5,1,2,3,4,5')),
                ('cohort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.cohort')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
