# Generated by Django 3.1.7 on 2021-12-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bout_planning_notification', '0021_levelsequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelsequence',
            name='user',
        ),
    ]
