# Generated by Django 3.1.7 on 2021-12-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bout_planning_notification', '0024_levelsequence_user_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelsequence',
            name='sequence_text',
            field=models.TextField(default='0,1,2,3,4,0,1,2,3,4'),
        ),
    ]
