# Generated by Django 3.1.7 on 2021-12-22 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0025_auto_20210909_0131'),
        ('bout_planning_notification', '0025_auto_20211222_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelSequenceBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_block', models.TextField(default=None, null=True)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('when_used', models.DateTimeField(default=None, null=True)),
                ('cohort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.cohort')),
            ],
        ),
    ]
