# Generated by Django 3.1.7 on 2022-07-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bout_planning_notification', '0026_levelsequenceblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='when_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
