# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-23 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_app', '0002_watchinstall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepcount',
            name='step_number',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
