# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-26 23:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='request_data',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_time',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='response_code',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='response_data',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='response_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='url',
            field=models.CharField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
