# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-10 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_auto_20190226_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='name',
            field=models.CharField(default='Unknown', editable=False, max_length=150),
            preserve_default=False,
        ),
    ]
