# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-21 00:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0003_servicerequest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
