# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-21 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0004_auto_20190621_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='request_data',
            field=models.TextField(editable=False, null=True),
        ),
    ]
