# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-21 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0005_auto_20190621_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='request_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
