# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-24 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0006_auto_20190621_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='url',
            field=models.CharField(editable=False, max_length=500),
        ),
    ]
