# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-13 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity_types', '0001_initial'),
        ('fitbit_api', '0022_fitbitactivity_average_heart_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitActivityToActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_types.ActivityType')),
                ('fitbit_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitActivityType')),
            ],
        ),
    ]
