# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-13 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitactivitytoactivitytype',
            name='fitbit_activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitActivityType'),
        ),
    ]
