# Generated by Django 3.1.7 on 2022-07-13 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitbit_activity_logs', '0004_auto_20190313_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbitactivitytoactivitytype',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
