# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-08-03 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_tasks', '0003_dailytask_day'),
        ('closeout_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='daily_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='daily_tasks.DailyTask'),
        ),
    ]
