dev: python ./manage.py runserver 0.0.0.0:8080
web: gunicorn -b :8080 heartsteps.wsgi:application --log-level debug
celery: celery worker -A heartsteps -l info -Q default,fitbit,messages
celeryFitbit: celery worker -A heartsteps -l info -Q fitbit
celeryMessages: celery worker -A heartsteps -l info -Q messages
celeryExport: celery worker -A heartsteps -l info -Q export
beat: celery beat -A heartsteps -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
cloudsql: /cloud_sql_proxy -dir=/cloudsql -instances=heartsteps-kpwhri:us-west1:heartsteps-kpw -credential_file=/credentials/google-service-account.json
