# Generated by Django 3.1.7 on 2021-12-29 01:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SupportingDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SupportingData',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='reports.report')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='reports.supportingdatatype')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSave',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='reports.report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_NULL, to='reports.reporttype'),
            preserve_default=False,
        ),
    ]
