# Generated by Django 3.1.7 on 2021-12-29 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20211229_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reporttype'),
        ),
        migrations.AlterField(
            model_name='reportsave',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.report'),
        ),
        migrations.AlterField(
            model_name='supportingdata',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.report'),
        ),
        migrations.AlterField(
            model_name='supportingdata',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.supportingdatatype'),
        ),
    ]
