# Generated by Django 3.1.7 on 2022-04-22 20:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0025_auto_20210909_0131'),
        ('reports', '0004_reportrecipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDesign',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('design', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.study')),
            ],
        ),
        migrations.CreateModel(
            name='ReportRenderLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='SUCCESS', max_length=255)),
                ('log', models.JSONField(default=dict)),
                ('report_design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reportdesign')),
            ],
        ),
    ]
