# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-09-22 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burst_periods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burstday',
            name='burst',
        ),
    ]
