# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-09-22 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('burst_periods', '0002_remove_burstday_burst'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurstPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='burstday',
            name='user',
        ),
        migrations.DeleteModel(
            name='BurstDay',
        ),
    ]
