# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-09-23 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burst_periods', '0003_auto_20200922_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='interval_buffer_length',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='configuration',
            name='interval_length',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='configuration',
            name='period_length',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
