# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-09-23 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burst_periods', '0004_auto_20200923_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='interval_buffer_length',
        ),
        migrations.AddField(
            model_name='configuration',
            name='interval_variation',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
