# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-10-21 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burst_periods', '0006_configuration_daily_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='burstperiod',
            options={'ordering': ['start', 'user']},
        ),
    ]
