# Generated by Django 3.1.7 on 2021-04-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burst_periods', '0007_auto_20201021_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
