# Generated by Django 3.1.7 on 2021-07-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='querystring',
            name='filter_pattern',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
