# Generated by Django 3.1.7 on 2021-07-02 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration_manager', '0002_querystring_filter_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querystring',
            name='level',
        ),
    ]
