# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-12 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'work'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
