# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-12 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20180912_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
