# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-30 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-time', 'user']},
        ),
    ]
