# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-22 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20181030_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'work'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
