# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartsteps_messages', '0002_auto_20180802_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
