# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartsteps_messages', '0003_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='message',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='user',
        ),
        migrations.DeleteModel(
            name='Decision',
        ),
    ]
