# Generated by Django 3.1.7 on 2021-05-20 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericMessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(max_length=100, null=True)),
                ('message_id', models.CharField(max_length=100, null=True)),
                ('message_title', models.TextField(null=True)),
                ('message_body', models.TextField(null=True)),
            ],
            options={
                'unique_together': {('parent_id', 'message_id')},
            },
        ),
        migrations.CreateModel(
            name='GenericMessageSentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_messages.genericmessagemodel')),
            ],
        ),
        migrations.CreateModel(
            name='GenericMessagesConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_messages_configuration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
