# Generated by Django 3.1.7 on 2021-05-20 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generic_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericmessagesentlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genericmessagesentlog',
            name='when',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
