# Generated by Django 3.1.7 on 2021-07-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0002_auto_20210712_0237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featureflags',
            options={'verbose_name': 'Feature Flags', 'verbose_name_plural': 'Feature Flags'},
        ),
    ]
