# Generated by Django 3.1.7 on 2022-06-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0006_auto_20211222_0405'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='featureflags',
            index=models.Index(fields=['user'], name='feature_fla_user_id_541ba7_idx'),
        ),
    ]
