# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-04 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='enjoyed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
