# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-14 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0004_auto_20190114_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylogsource',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
