# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-28 03:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_logs', '0006_auto_20190114_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogsource',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
