# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-21 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_gen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockfacepin',
            name='pin',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
