# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-10 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin_gen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='pin',
            new_name='pin_digits',
        ),
    ]
