# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-30 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_gen', '0003_auto_20200721_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockfacepin',
            name='uniid',
            field=models.CharField(default='null', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clockfacepin',
            name='pin',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
