# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-30 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin_gen', '0004_auto_20200730_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clockfacepin',
            name='uniid',
        ),
    ]
