# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-30 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pin_gen', '0005_remove_clockfacepin_uniid'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockfacepin',
            name='uniid',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
