# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='firebase_token',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
