# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-28 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='birth_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='enrollment_token',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='heartsteps_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
