# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0003_auto_20170313_1314'),
        ('participants', '0002_participant_firebase_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='firebase_token',
        ),
        migrations.AddField(
            model_name='participant',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fcm_django.FCMDevice'),
        ),
    ]
