# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-29 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_dailytask_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='day_end',
            field=models.CharField(default='20:00', max_length=10),
        ),
        migrations.AddField(
            model_name='participant',
            name='day_start',
            field=models.CharField(default='8:00', max_length=10),
        ),
        migrations.AddField(
            model_name='participant',
            name='timezone',
            field=models.CharField(default='UTC', max_length=25),
        ),
    ]
