# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 21:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_auto_20180703_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='device',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='id',
        ),
        migrations.AddField(
            model_name='participant',
            name='heartsteps_id',
            field=models.CharField(default='fake', max_length=25, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
