# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-29 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_auto_20181129_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='timezone',
        ),
        migrations.AddField(
            model_name='dailytask',
            name='hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='minute',
            field=models.IntegerField(null=True),
        ),
    ]
