# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-30 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_auto_20181129_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyTask',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
