# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-20 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_auto_20181130_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='day_end',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='day_start',
        ),
    ]
