# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-09-02 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_auto_20181220_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.Cohort'),
        ),
    ]
