# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-10-14 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0009_auto_20190920_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='baseline_period',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='study',
            name='contact_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
