# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-10-14 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0010_auto_20191014_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
