# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-08-04 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0014_cohort_study_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='study_start_date',
            field=models.DateField(null=True),
        ),
    ]
