# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-08-23 01:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participants', '0015_participant_study_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightlyUpdateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('error', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='nightlyupdaterecord',
            index=models.Index(fields=['user', 'date'], name='participant_user_id_1e7810_idx'),
        ),
    ]
