# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-10-05 01:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participants', '0016_auto_20200823_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExportSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('last_data_export', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='participants.DataExport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
