# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-10-27 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0018_dataexportqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='export_data',
            field=models.BooleanField(default=True),
        ),
    ]
