# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-11-29 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0019_cohort_export_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='export_bucket_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='export_data',
            field=models.BooleanField(default=False),
        ),
    ]
