# Generated by Django 3.1.7 on 2021-08-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0022_auto_20210813_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='cohort_feature_flags',
            field=models.TextField(default=''),
        ),
    ]
