# Generated by Django 3.1.7 on 2021-08-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0023_cohort_cohort_feature_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='export_bucket_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='study_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
