# Generated by Django 3.1.7 on 2021-09-09 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0024_auto_20210819_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='cohort_feature_flags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.study'),
        ),
        migrations.AlterField(
            model_name='study',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='name',
            field=models.CharField(blank=True, max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='studywide_feature_flags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
