# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-11-24 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20190413_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
