# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-24 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('likert', 'Likert question'), ('select-one', 'select_one'), ('select-many', 'select_many')], default='likert', max_length=75),
        ),
    ]
