# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-24 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_question_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='kind',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('likert', 'Likert question'), ('select-one', 'Select one question')], default='likert', max_length=25),
        ),
    ]
