# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-11-02 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_auto_20200324_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
