# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-19 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
