# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-19 00:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitAccount',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('fitbit_user', models.CharField(max_length=32, unique=True)),
                ('access_token', models.TextField(help_text='The OAuth2 access token')),
                ('refresh_token', models.TextField(help_text='The OAuth2 refresh token')),
                ('expires_at', models.FloatField(help_text='The timestamp when the access token expires')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FitbitSubscription',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('fitbit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitAccount')),
            ],
        ),
    ]
