# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-18 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitapp', '0009_auto_20180918_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitAccount',
            fields=[
                ('userfitbit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fitapp.UserFitbit')),
            ],
            bases=('fitapp.userfitbit',),
        ),
        migrations.CreateModel(
            name='FitbitSubscription',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('fitbit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitAccount')),
            ],
        ),
    ]
