# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-09 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0003_fitbitsubscriptionupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitbitsubscription',
            name='active',
        ),
    ]
