# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-10 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0004_remove_fitbitsubscription_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitActivity',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('fitbit_id', models.CharField(max_length=50)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitAccount')),
            ],
        ),
        migrations.CreateModel(
            name='FitbitActivityType',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('fitbit_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FitbitDay',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('active_minutes', models.FloatField(default=0)),
                ('total_steps', models.FloatField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitAccount')),
            ],
        ),
        migrations.CreateModel(
            name='FitbitMinuteStepCount',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('steps', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitAccount')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitDay')),
            ],
        ),
        migrations.AddField(
            model_name='fitbitactivity',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitDay'),
        ),
    ]
