# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-15 17:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0006_auto_20181010_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitUpdate',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
