# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-17 02:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0008_auto_20181017_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbitactivity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitbitactivity',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitbitactivity',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitActivityType'),
        ),
        migrations.AddField(
            model_name='fitbitactivity',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
