# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-18 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0009_auto_20181017_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenticationsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='AuthenticationSession',
        ),
    ]
