# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-05 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0011_fitbitdailystepsunprocessed_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbitday',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
            preserve_default=False,
        ),
    ]
