# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-07 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0012_fitbitday_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbitactivity',
            name='vigorous_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
