# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-07 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0013_fitbitactivity_vigorous_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitbitactivity',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='fitbitactivity',
            old_name='startTime',
            new_name='start_time',
        ),
    ]
