# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-07 03:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0014_auto_20181107_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitDailyUnprocessedData',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitAccount')),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitDay')),
            ],
        ),
        migrations.RemoveField(
            model_name='fitbitdailystepsunprocessed',
            name='account',
        ),
        migrations.RemoveField(
            model_name='fitbitdailystepsunprocessed',
            name='day',
        ),
        migrations.DeleteModel(
            name='FitbitDailyStepsUnprocessed',
        ),
    ]
