# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-13 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0015_auto_20181107_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitbitday',
            old_name='total_steps',
            new_name='step_count',
        ),
        migrations.RemoveField(
            model_name='fitbitday',
            name='active_minutes',
        ),
        migrations.AddField(
            model_name='fitbitactivity',
            name='moderate_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitbitday',
            name='moderate_minutes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fitbitday',
            name='vigorous_minutes',
            field=models.FloatField(default=0),
        ),
    ]
