# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-12 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0016_auto_20181113_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbitsubscriptionupdate',
            name='update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitUpdate'),
        ),
    ]
