# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-12 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0018_auto_20181212_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitaccount',
            name='fitbit_user',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
