# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-06 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0019_auto_20181212_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitday',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
