# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-13 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0020_auto_20190106_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitbitactivity',
            name='moderate_minutes',
        ),
        migrations.RemoveField(
            model_name='fitbitactivity',
            name='vigorous_minutes',
        ),
        migrations.RemoveField(
            model_name='fitbitday',
            name='moderate_minutes',
        ),
        migrations.RemoveField(
            model_name='fitbitday',
            name='vigorous_minutes',
        ),
    ]
