# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-13 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0021_auto_20190113_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbitactivity',
            name='average_heart_rate',
            field=models.IntegerField(null=True),
        ),
    ]
