# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-14 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0022_fitbitactivity_average_heart_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitbitday',
            name='step_count',
        ),
        migrations.AddField(
            model_name='fitbitday',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitbitday',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
