# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-15 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0023_auto_20190114_0045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitbitupdate',
            options={'ordering': ['created']},
        ),
    ]
