# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-15 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0025_auto_20190115_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitbitday',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='fitbitday',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
