# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-29 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0026_auto_20190115_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitday',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fitbitday',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
