# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-05 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0028_fitbitminutedistance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitbitminutestepcount',
            name='day',
        ),
    ]
