# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-05 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0029_remove_fitbitminutestepcount_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbitday',
            name='distance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='fitbitday',
            name='step_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
