# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-05 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0030_auto_20190205_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitbitday',
            old_name='timezone',
            new_name='_timezone',
        ),
    ]
