# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-05 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0031_auto_20190205_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitbitminutedistance',
            name='account',
        ),
        migrations.DeleteModel(
            name='FitbitMinuteDistance',
        ),
    ]
