# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-05 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0032_auto_20190205_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbitday',
            name='average_heart_rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
