# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-05 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0033_fitbitday_average_heart_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitday',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
