# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-05 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0034_auto_20190205_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitday',
            name='distance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
    ]
