# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-05 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0035_auto_20190205_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitbitday',
            old_name='distance',
            new_name='_distance',
        ),
    ]
