# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-05 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0036_auto_20190205_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitdailyunprocesseddata',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitDay'),
        ),
    ]
