# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-11 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0037_auto_20190205_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitactivity',
            name='fitbit_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='fitbitactivitytype',
            name='fitbit_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='fitbitdailyunprocesseddata',
            unique_together=set([('day', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='fitbitday',
            unique_together=set([('account', 'date')]),
        ),
    ]
