# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-11 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0038_auto_20190211_0248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitbitactivity',
            options={'ordering': ['start_time']},
        ),
    ]
