# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-27 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0039_auto_20190211_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitbitactivity',
            name='day',
        ),
    ]
