# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-27 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0040_remove_fitbitactivity_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fitbitactivity',
            unique_together=set([('account', 'fitbit_id')]),
        ),
    ]
