# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-27 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0041_auto_20190227_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitactivity',
            name='fitbit_id',
            field=models.CharField(max_length=50),
        ),
    ]
