# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-28 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_activity_logs', '0003_auto_20190228_0054'),
        ('fitbit_api', '0042_auto_20190227_2241'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fitbitactivity',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='fitbitactivity',
            name='account',
        ),
        migrations.RemoveField(
            model_name='fitbitactivity',
            name='type',
        ),
        migrations.AlterUniqueTogether(
            name='fitbitdailyunprocesseddata',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='fitbitdailyunprocesseddata',
            name='account',
        ),
        migrations.RemoveField(
            model_name='fitbitdailyunprocesseddata',
            name='day',
        ),
        migrations.AlterUniqueTogether(
            name='fitbitday',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='fitbitday',
            name='account',
        ),
        migrations.RemoveField(
            model_name='fitbitminutestepcount',
            name='account',
        ),
        migrations.DeleteModel(
            name='FitbitActivity',
        ),
        migrations.DeleteModel(
            name='FitbitActivityType',
        ),
        migrations.DeleteModel(
            name='FitbitDailyUnprocessedData',
        ),
        migrations.DeleteModel(
            name='FitbitDay',
        ),
        migrations.DeleteModel(
            name='FitbitMinuteStepCount',
        ),
    ]
