# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-09-29 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0043_auto_20190228_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitAccountUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fitbit_api.FitbitAccount')),
                ('update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitbit_api.FitbitUpdate')),
            ],
            options={
                'ordering': ['completed', 'created'],
            },
        ),
    ]
