# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-09-29 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0044_fitbitaccountupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitbitaccountupdate',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='fitbitaccountupdate',
            name='completed',
        ),
    ]
