# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-01-04 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0046_fitbitdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitDeviceUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('battery_level', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fitbit_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit_api.FitbitDevice')),
            ],
        ),
    ]
