# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-10 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0048_auto_20200104_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitdevice',
            name='device_type',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='fitbitdevice',
            name='device_version',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='fitbitdevice',
            name='mac',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
