# Generated by Django 3.1.7 on 2021-03-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0050_auto_20200210_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitsubscriptionupdate',
            name='payload',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='fitbitupdate',
            name='payload',
            field=models.JSONField(),
        ),
    ]
