# Generated by Django 3.1.7 on 2021-04-13 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0051_auto_20210306_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitAccountSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fitbit_api.fitbitaccount')),
                ('first_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fitbit_api.fitbitaccountupdate')),
                ('last_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fitbit_api.fitbitaccountupdate')),
            ],
        ),
    ]
