# Generated by Django 3.1.7 on 2022-03-18 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitbit_api', '0054_fitbitaccountuserhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitaccountuserhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
