# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-04 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_survey_answered'),
        ('activity_surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySurveyQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.Question')),
            ],
            bases=('surveys.question',),
        ),
    ]
