# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-25 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity_surveys', '0004_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysurvey',
            name='decision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activity_surveys.Decision'),
        ),
        migrations.AddField(
            model_name='decision',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decision',
            name='treated',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decision',
            name='treatment_probability',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decision',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
