# Generated by Django 3.1.7 on 2021-03-06 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_activities', '0006_fitbitday_minutes_worn'),
        ('activity_surveys', '0006_configuration_treatment_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='activity_survey_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='decision',
            name='fitbit_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fitbit_activities.fitbitactivity'),
        ),
    ]
