# Generated by Django 3.1.7 on 2021-03-14 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_messages', '0010_auto_20210306_1849'),
        ('activity_surveys', '0008_auto_20210306_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='push_messages.message'),
        ),
    ]
