# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-14 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anti_seds', '0002_remove_stepcount_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stepcount',
            old_name='step_count',
            new_name='step_number',
        ),
    ]
