# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-10 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomization', '0008_decision_test'),
        ('anti_seds', '0004_antisedentarydecision_antisedentarymessagetemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antisedentarydecision',
            name='decision_ptr',
        ),
        migrations.RemoveField(
            model_name='antisedentarymessagetemplate',
            name='messagetemplate_ptr',
        ),
        migrations.DeleteModel(
            name='AntiSedentaryDecision',
        ),
        migrations.DeleteModel(
            name='AntiSedentaryMessageTemplate',
        ),
    ]
