# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-10 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anti_seds', '0005_auto_20190110_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepcount',
            options={'ordering': ['-step_dtm']},
        ),
    ]
