# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-11 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=20)),
                ('battery', models.CharField(max_length=20)),
                ('device_version', models.CharField(max_length=20)),
                ('last_sync_dtm', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackerActivityCalories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_dt', models.DateField()),
                ('tracker_tm', models.TimeField()),
                ('tracker_tz', models.CharField(max_length=48)),
                ('calories', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackers.Tracker')),
            ],
        ),
        migrations.CreateModel(
            name='TrackerActivitySteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_dt', models.DateField()),
                ('tracker_tm', models.TimeField()),
                ('tracker_tz', models.CharField(max_length=48)),
                ('steps', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackers.Tracker')),
            ],
        ),
        migrations.CreateModel(
            name='TrackerBodyWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_dt', models.DateField()),
                ('tracker_tm', models.TimeField()),
                ('tracker_tz', models.CharField(max_length=48)),
                ('source', models.CharField(max_length=24)),
                ('bmi', models.FloatField()),
                ('weight', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackers.Tracker')),
            ],
        ),
        migrations.CreateModel(
            name='TrackerHeartRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_dt', models.DateField()),
                ('tracker_tm', models.TimeField()),
                ('tracker_tz', models.CharField(max_length=48)),
                ('dataset_interval', models.FloatField()),
                ('dataset_type', models.CharField(max_length=24)),
                ('weight', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackers.Tracker')),
            ],
        ),
        migrations.CreateModel(
            name='TrackerOAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=64)),
                ('refresh_token', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackers.Tracker')),
            ],
        ),
        migrations.CreateModel(
            name='TrackerSleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_dt', models.DateField()),
                ('total_minutes_asleep', models.IntegerField()),
                ('total_sleep_records', models.IntegerField()),
                ('total_time_in_bed', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackers.Tracker')),
            ],
        ),
    ]
