# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-07 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adherence_messages', '0003_auto_20190707_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='enabled',
        ),
        migrations.AddField(
            model_name='configuration',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='date_initialized',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
