# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-07 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence_messages', '0004_auto_20190707_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
