# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-07 22:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adherence_messages', '0005_configuration_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdherenceDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyadherencemetric',
            name='day',
        ),
        migrations.RemoveField(
            model_name='dailyadherencemetric',
            name='user',
        ),
        migrations.AddField(
            model_name='dailyadherencemetric',
            name='adherence_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adherence_messages.AdherenceDay'),
        ),
    ]
