# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-08 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adherence_messages', '0006_auto_20190707_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='date_initialized',
        ),
    ]
