# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-08 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence_messages', '0008_adherencemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherencemessage',
            name='category',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
