# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-09 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adherence_messages', '0010_auto_20190709_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdherenceMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('wore-fitbit', 'Wore fitbit'), ('app-used', 'Used app'), ('app-installed', 'Installed app')], max_length=70)),
                ('value', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='adherenceday',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dailyadherencemetric',
            name='adherence_day',
        ),
        migrations.RemoveField(
            model_name='adherencemessage',
            name='adherence_day',
        ),
        migrations.AddField(
            model_name='adherencemessage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdherenceDay',
        ),
        migrations.DeleteModel(
            name='DailyAdherenceMetric',
        ),
    ]
