# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-16 22:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adherence_messages', '0011_auto_20190709_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdherenceAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
                ('category', models.CharField(max_length=70)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='adherencemessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdherenceMessage',
        ),
    ]
