# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-16 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_messages', '0002_message_body'),
        ('adherence_messages', '0012_auto_20190716_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdherenceMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('adherence_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adherence_messages.AdherenceAlert')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_messages.Message')),
            ],
        ),
    ]
