# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-23 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adherence_messages', '0013_adherencemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adherencealert',
            name='user',
        ),
        migrations.RemoveField(
            model_name='adherencemessage',
            name='adherence_alert',
        ),
        migrations.RemoveField(
            model_name='adherencemessage',
            name='message',
        ),
        migrations.DeleteModel(
            name='AdherenceAlert',
        ),
        migrations.DeleteModel(
            name='AdherenceMessage',
        ),
    ]
