# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-23 21:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_messages', '0002_message_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adherence_messages', '0014_auto_20190723_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdherenceMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('wore-fitbit', 'Wore fitbit'), ('app-used', 'Used app'), ('app-installed', 'Installed app')], max_length=70, null=True)),
                ('body', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_messages.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
