# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-24 22:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adherence_messages', '0015_adherencemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherencemessage',
            name='category',
            field=models.CharField(choices=[('app-installed', 'App installed'), ('app-used', 'App used'), ('fitbit-updated', 'Fitbit updated'), ('fitbit-worn', 'Fitbit worn')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='adherencemessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adherencemetric',
            name='category',
            field=models.CharField(choices=[('app-installed', 'App installed'), ('app-used', 'App used'), ('fitbit-updated', 'Fitbit updated'), ('fitbit-worn', 'Fitbit worn')], max_length=70, null=True),
        ),
    ]
