# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-06 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_summaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='total_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
