# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-09-03 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_summaries', '0003_day_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='activities_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
