# Generated by Django 3.1.7 on 2021-03-31 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_summaries', '0005_auto_20190906_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities_completed', models.PositiveIntegerField(default=0)),
                ('miles', models.PositiveIntegerField(default=0)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('steps', models.PositiveIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='activitysummary',
            index=models.Index(fields=['user'], name='activity_su_user_id_dda291_idx'),
        ),
    ]
