# Generated by Django 3.1.7 on 2021-03-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_summaries', '0006_auto_20210331_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysummary',
            name='miles',
            field=models.FloatField(default=0),
        ),
    ]
