# Generated by Django 3.1.7 on 2022-06-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_summaries', '0008_auto_20211202_1833'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='day',
            index=models.Index(fields=['user', 'date'], name='activity_su_user_id_0c467c_idx'),
        ),
    ]
