# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-04 22:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('start_time', models.CharField(max_length=15)),
                ('activity_type', models.CharField(max_length=50)),
                ('intensity', models.CharField(choices=[('m', 'Moderate'), ('v', 'Vigorous')], max_length=1)),
                ('duration', models.IntegerField()),
                ('complete', models.BooleanField(default=False)),
                ('enjoyed', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
