# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-05 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0002_auto_20190104_1947'),
        ('activity_plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityplan',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='enjoyed',
        ),
        migrations.AddField(
            model_name='activityplan',
            name='activity_log',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_logs.ActivityLog'),
        ),
    ]
