# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-08 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='enjoyed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
