# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-12 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_plans', '0002_auto_20190105_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityplan',
            name='activity_log',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_logs.ActivityLog'),
        ),
    ]
