# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-12 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_plans', '0003_auto_20180912_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityplan',
            old_name='isComplete',
            new_name='complete',
        ),
    ]
