# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-09-02 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0004_auto_20190901_2137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='day',
            unique_together=set([]),
        ),
    ]
