# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-09-06 22:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0006_auto_20190906_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
