# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-18 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationSession',
            fields=[
                ('token', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
