# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-24 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_authorize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationsession',
            name='redirect',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
