# Generated by Django 3.1.7 on 2022-03-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipcode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipcoderequesthistory',
            name='centroid_address',
        ),
        migrations.AddField(
            model_name='zipcoderequesthistory',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zipcoderequesthistory',
            name='response_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='zipcoderequesthistory',
            name='response_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zipcoderequesthistory',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zipcoderequesthistory',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='zipcoderequesthistory',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
