# Generated by Django 3.1.7 on 2022-03-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipcode', '0002_auto_20220325_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcoderequesthistory',
            name='response_message',
            field=models.TextField(null=True),
        ),
    ]
