# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-25 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('heartsteps_randomization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='heartsteps_randomization.Decision')),
            ],
        ),
    ]
