# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-25 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heartsteps_randomization', '0002_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='heartsteps_messages.Message'),
        ),
    ]
