# Generated by Django 3.1.7 on 2021-12-24 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0025_auto_20210909_0131'),
        ('sms_messages', '0002_message_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioAccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sid', models.CharField(max_length=200)),
                ('auth_token', models.CharField(max_length=200)),
                ('study', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='participants.study')),
            ],
        ),
    ]
