# Generated by Django 3.1.7 on 2021-12-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_messages', '0003_twilioaccountinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='twilioaccountinfo',
            name='from_phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='twilioaccountinfo',
            name='account_sid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='twilioaccountinfo',
            name='auth_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
