# Generated by Django 3.1.7 on 2021-07-03 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_clock_face', '0002_clockfacestepcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockfacestepcount',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clockfacestepcount',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
