# Generated by Django 3.1.7 on 2021-07-05 21:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitbit_clock_face', '0003_auto_20210703_0047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClockFaceStepCount',
            new_name='ClockFaceLog',
        ),
    ]
