# Generated by Django 3.1.7 on 2021-07-05 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_clock_face', '0005_stepcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clockfacelog',
            options={'ordering': ['time']},
        ),
    ]
