# Generated by Django 3.1.7 on 2021-07-31 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitbit_clock_face', '0006_auto_20210705_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_face', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fitbit_clock_face.clockface')),
                ('last_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fitbit_clock_face.clockfacelog')),
                ('last_step_count', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fitbit_clock_face.stepcount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
