# Generated by Django 3.1.7 on 2021-07-31 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20200803_1828'),
        ('fitbit_clock_face', '0007_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='last_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location'),
        ),
    ]
