# Generated by Django 3.1.7 on 2021-10-28 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_step_goals', '0004_stepgoalprbscsv'),
        ('fitbit_clock_face', '0008_summary_last_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='last_step_goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='daily_step_goals.stepgoal'),
        ),
    ]
