# Generated by Django 3.1.7 on 2021-10-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_clock_face', '0009_summary_last_step_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockfacelog',
            name='step_goal',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
