# Generated by Django 3.1.7 on 2021-10-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_clock_face', '0010_clockfacelog_step_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockfacelog',
            name='step_goal',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
