# Generated by Django 3.1.7 on 2021-11-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_clock_face', '0011_auto_20211029_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clockfacelog',
            name='step_goal',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='last_step_goal',
        ),
    ]
