# Generated by Django 3.1.7 on 2021-07-15 10:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_summaries', '0007_auto_20210331_1910'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daily_step_goals', '0002_days'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Days',
            new_name='ActivityDay',
        ),
        migrations.RenameModel(
            old_name='StepGoals',
            new_name='StepGoal',
        ),
    ]
