# Generated by Django 3.1.7 on 2021-09-09 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0024_auto_20210819_0310'),
        ('daily_step_goals', '0003_auto_20210715_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepGoalPRBScsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRBS_text', models.TextField(blank=True, null=True)),
                ('when_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('delimiter', models.CharField(default=',', max_length=10)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.cohort')),
            ],
        ),
    ]
