# Generated by Django 3.1.7 on 2021-11-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_step_goals', '0004_stepgoalprbscsv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityDay',
        ),
    ]
