# Generated by Django 3.1.7 on 2021-12-17 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0025_auto_20210909_0131'),
        ('daily_step_goals', '0006_stepgoalsevidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepGoalCalculationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitude', models.IntegerField(default=2000)),
                ('base_jump', models.IntegerField(default=0)),
                ('maximum', models.IntegerField(default=30000)),
                ('minimum', models.IntegerField(default=100)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.cohort')),
            ],
        ),
    ]
