# Generated by Django 3.1.7 on 2021-12-17 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0025_auto_20210909_0131'),
        ('daily_step_goals', '0008_auto_20211217_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepgoalcalculationsettings',
            name='cohort',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='participants.cohort'),
        ),
    ]
