# Generated by Django 3.1.7 on 2021-12-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_step_goals', '0010_auto_20211217_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepgoalsevidence',
            name='base_jump',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stepgoalsevidence',
            name='magnitude',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='stepgoalsevidence',
            name='maximum',
            field=models.IntegerField(default=30000),
        ),
        migrations.AddField(
            model_name='stepgoalsevidence',
            name='minimum',
            field=models.IntegerField(default=100),
        ),
    ]
