# Generated by Django 3.1.7 on 2021-12-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_step_goals', '0011_auto_20211217_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepgoal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
