# Generated by Django 3.1.7 on 2022-03-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_step_goals', '0014_auto_20220114_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepgoalcalculationsettings',
            name='magnitude',
            field=models.IntegerField(default=4000),
        ),
        migrations.AlterField(
            model_name='stepgoalcalculationsettings',
            name='maximum',
            field=models.IntegerField(default=8000),
        ),
        migrations.AlterField(
            model_name='stepgoalcalculationsettings',
            name='minimum',
            field=models.IntegerField(default=2000),
        ),
    ]
