# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-09-07 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_views', '0002_auto_20190907_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='build_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='platform',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='version',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
