# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-09-07 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_views', '0003_auto_20190907_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
