# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-09-07 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_views', '0004_auto_20190907_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageview',
            old_name='build_number',
            new_name='build',
        ),
    ]
