# Generated by Django 3.1.7 on 2021-04-14 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page_views', '0005_auto_20190907_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_page_view', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='page_views.pageview')),
                ('last_page_view', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='page_views.pageview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
