# Generated by Django 3.1.7 on 2021-05-21 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0014_remove_clockedschedule_enabled'),
        ('hourly_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlytask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
