# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('behavioral_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255)),
                ('context_tags', models.ManyToManyField(to='behavioral_messages.ContextTag')),
            ],
        ),
        migrations.CreateModel(
            name='MorningMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morning_messages.AnchorMessage')),
                ('context_tags', models.ManyToManyField(to='behavioral_messages.ContextTag')),
                ('message_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='behavioral_messages.MessageTemplate')),
            ],
        ),
    ]
