# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-24 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morning_messages', '0002_morningmessagedecision_morningmessagetemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anchormessage',
            name='context_tags',
        ),
        migrations.RemoveField(
            model_name='morningmessage',
            name='anchor_message',
        ),
        migrations.RemoveField(
            model_name='morningmessage',
            name='context_tags',
        ),
        migrations.RemoveField(
            model_name='morningmessage',
            name='message_template',
        ),
        migrations.DeleteModel(
            name='AnchorMessage',
        ),
        migrations.DeleteModel(
            name='MorningMessage',
        ),
    ]
