# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-19 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morning_messages', '0005_configuration_daily_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='morningmessagedecision',
            name='framing',
            field=models.CharField(choices=[('gain and active', 'gain and active'), ('gain and sedentary', 'gain and sedentary'), ('loss and active', 'loss and active'), ('loss and secentary', 'loss and secentary')], editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='daily_task',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='morning_message_configuration', to='daily_tasks.DailyTask'),
        ),
    ]
