# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-15 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('morning_messages', '0006_auto_20181219_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorningMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message_decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morning_messages.MorningMessageDecision')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
