# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-15 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morning_messages', '0007_morningmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='morningmessage',
            name='anchor',
            field=models.CharField(editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='morningmessage',
            name='notification',
            field=models.CharField(editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='morningmessage',
            name='randomized',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='morningmessage',
            name='text',
            field=models.CharField(editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='morningmessage',
            name='message_decision',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='morning_messages.MorningMessageDecision'),
        ),
    ]
