# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-16 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morning_messages', '0008_auto_20190115_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morningmessage',
            name='anchor',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='morningmessage',
            name='notification',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='morningmessage',
            name='text',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
