# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-14 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20190413_2320'),
        ('morning_messages', '0009_auto_20190116_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorningMessageQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.Question')),
            ],
            bases=('surveys.question',),
        ),
        migrations.CreateModel(
            name='MorningMessageSurvey',
            fields=[
                ('survey_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.Survey')),
            ],
            bases=('surveys.survey',),
        ),
        migrations.AddField(
            model_name='morningmessage',
            name='survey',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='morning_messages.MorningMessageSurvey'),
        ),
    ]
