# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-05 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morning_messages', '0010_auto_20190414_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='morningmessagesurvey',
            name='word_set_string',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
