# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-31 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('morning_messages', '0012_morningmessagesurvey_selected_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorningMessageContextObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('morning_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='morning_messages.MorningMessage')),
            ],
        ),
    ]
